// created on: Apr 17, 2008
package NodeRules

// list any import classes here.
import edu.cuny.citytech.analyzecommonality.core.analysis.graph.*;
import ca.mcgill.cs.swevo.jayfx.model.*;

// declare any global variables here
global Integer maximumAnalysisDepth

// Two nodes are connected when there is an arc in between them. (base case).
rule "connected"
	when
		$arc : IntentionArc()
	then
		Path<IntentionArc<IElement>> aPath = new Path<IntentionArc<IElement>>();
		aPath.push($arc);
		insert(aPath);
end

rule "path building"
	when
		$arc : IntentionArc($source : fromNode, $target : toNode)
		$path : Path(size < maximumAnalysisDepth, topNode == $target, tailNodes not contains $source) // TODO: more work here?
	then
		Path aPath = (Path)$path.clone();
		aPath.push($arc);
		insert(aPath);
end

query "all paths"
	$path : Path()
end

query "forward suggested execution nodes"
	$enabledNode : IntentionNode()
end